# MAIN
title:               DAKTYLOS
# description:         S1SYPHOS.github.io description
url:                 http://localhost:3000
paginate:            5
baseurl:             /
source:             source
destination:        build
environment:        development

# ABOUT / CONTACT
author:
  name:              S1SYPHOS
  email:             hello@daktylos.net

# MISC
version:             0.0.1
github:
  repo:              https://github.com/S1SYPHOS/S1SYPHOS.github.io
