# SITE SETTINGS
title: 'Frasco: Jekyll Starter Project'
description: Quick starter project for Jekyll including full setup for gulp, Sass, Autoprefixer, Bourbon/Neat/Bitters, Webpack, Imagemin, Browsersync, etc.
url: https://ixkaito.github.io # the base hostname & protocol for your site
baseurl: '/frasco' # the subpath of your site, e.g. /blog

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
source: source
destination: build
include: ['_pages']
